export const PAK_UNIVERSITIES = [
    "University of Agriculture Faisalabad (UAF)",
    "University of the Punjab (PU) - Lahore",
    "University of Engineering and Technology (UET) - Lahore",
    "National University of Sciences & Technology (NUST) - Islamabad",
    "COMSATS University Islamabad (CUI)",
    "FAST-NUCES",
    "GIKI (Ghulam Ishaq Khan Institute)",
    "LUMS",
    "Quaid-i-Azam University (QAU)",
    "Information Technology University (ITU) - Lahore",
    "Government College University (GCU) - Lahore",
    "The Islamia University of Bahawalpur (IUB)",
    "University of Karachi (UoK)",
    "NED University of Engineering & Technology",
    "Institute of Business Administration (IBA) - Karachi",
    "University of Peshawar",
    "University of Sindh (UoS) - Jamshoro",
    "Bahauddin Zakariya University (BZU) - Multan",
    "International Islamic University (IIUI) - Islamabad",
    "Air University - Islamabad",
];

export const DEGREE_LEVELS = [
    { label: "BS", value: "BS" },
    { label: "MS", value: "MS" },
    { label: "PhD", value: "PHD" },
    { label: "Diploma", value: "DIPLOMA" },
    { label: "Other", value: "OTHER" },
];

export const COMMON_DEPARTMENTS = [
    "Computer Science",
    "Information Technology",
    "Software Engineering",
    "Data Science",
    "Cyber Security",
    "Artificial Intelligence",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Business Administration (BBA/MBA)",
    "Accounting & Finance",
    "Economics",
    "English",
    "Mass Communication / Media Studies",
    "Psychology",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biotechnology",
    "Agriculture",
];

export const DEGREE_PROGRAMS = [
    "BS Information Technology (BS IT)",
    "BS Computer Science (BSCS)",
    "BS Software Engineering (BSSE)",
    "BS Data Science (BS DS)",
    "BS Cyber Security",
    "BBA",
    "MBA",
    "MS Computer Science (MSCS)",
    "MS Information Technology (MS IT)",
];
